config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'

  resource :welcome, only: :index
  get 'welcome/query_by_filter', as: 'query_by_filter'
  get 'welcome/autocomplete_by_filter_tag', as: 'autocomplete_by_filter_tag'
  match 'welcome/search', as: 'search', via: [:get, :post]
  match 'welcome/suggest', as: 'suggest', via: [:get, :post]
  match 'welcome/search_disambig', as: 'search_disambig', via: [:get, :post]
  match 'outline/:id' => 'projects#outline', as: 'outline', via: [:get, :post]
  match 'outline_download/:id' => 'projects#outline_download', as: 'outline_download', via: [:get]

  resources :queries, only: [:show, :destroy] do
    member do
      get 'show'
      post 'show'
    end
  end

  resources :projects, except: [:new] do
    resources :queries, only: [:create]
    resources :ignored_items, only: [:create]
  end

  resources :ignored_items, only: [:destroy]

  resources :response_items, only: [] do
    member do
      post :toggle_favorite
    end
  end

  resources :timelines, only: :index do
    collection do
      get :data
    end
  end
end

app/views/shared/_breadcrumbs.html.haml
- if @sara_mode == :suggest || @sara_mode == :search
  .navigation-area{style: @sara_mode == :search ? 'background-color: transparent;' : ''}
    .navigation
      %button.sara-button.button-primary.back-button
        .by-icon-v02> 2
        = t('nav.back_home')
      - if @sara_mode == :suggest
        .breadcrumbs
          .by-icon-v02 1
          - if @base_query.present?
            .breadcrumbs-text
              %a{href: suggest_path}= t('nav.suggest_topics')
            .by-icon-v02 1
            .breadcrumbs-text
              = @base_query['title']
          - else
            .breadcrumbs-text.active
              %a= t('nav.suggest_topics')
- if @sara_mode == :outline
  .navigation-area
    .navigation
      %button.sara-button.button-primary.back-button
        .by-icon-v02> 2
        = t(:back_to_favorites)

app/views/shared/_menu_item.html.haml
- if node['nodetype'] == 'branch' && node['nodes'].present?
  %div{class: "vertical-expand level-#{level} fcoll", "data-bs-target" => "#collf_#{level}_#{ordinal}", "data-bs-toggle" => "collapse", title: node['description']}
    %p.headline-4= node['title']
  .nested.collapse{id: "collf_#{level}_#{ordinal}", 'data-bs-parent' => parent}
    .nested-content.nested-list
      - ordinal = 0
      - node['nodes'].each do |inode|
        - ordinal += 1
        = render partial: 'shared/menu_item', locals: { node: inode, level: level + 1, ordinal: ordinal, parent: "#collf_#{level}_#{ordinal}" }
- elsif node['nodetype'] == 'wikidata_query' && node['base_query'].present?
  = link_to search_disambig_path(base_query: node['base_query']), {style:'text-decoration: none;'} do
    %div{class: "vertical-expand level-#{level} fcoll", title: node['description']}
      %p.headline-4= node['title']
- else
  = 'TBD'

app/views/shared/_top_bar.html.haml
%header
  #header
    .header-general-area
      .header-general
        .top-right-c
          %a.top-logo{href: '/'}
          .top-gap-placeholder
          .top-search-switch
            %a{href: search_path, class: 'top-search-option right' + (@sara_mode == :search ? ' active' : ''), style:'color:white; text-decoration: none;'}
              %div= t('nav.focused_search')
            %a{href: suggest_path, class: 'top-search-option left' + (@sara_mode == :suggest ? ' active' : ''), style:'color:white; text-decoration: none;'}
              %div= t('nav.suggest_topics')
          .statistics-box
            .statistics
              .stat-big.stat-number 7
              .stat-small= t(:databases)
            .statistics
              .stat-big.stat-number= t(:about_8_million)
              .stat-small= t(:data_items)
        .top-left-content
          %a.white.by-icon-v02{:title => "שיתוף עמוד נוכחי"} U
          .icons-seperator
          .collapsed.user-menu-trigger{"data-target" => "#user_collapsible", "data-toggle" => "collapse", :title => "תפריט המשתמש"}
            %div
              = link_to projects_path, {style:'color:white'} do
                שלום
                = succeed "!" do
                  %span.bold-text גלית כהן
            .by-icon-v02 )
            #user-actions-menu.dropdown-content.dropdown-menu{"x-placement" => "bottom-start"}
              %a{:href => ""}
                %span.by-icon-v02> D
                שאילתות אחרונות
              %a{:href => ""}
                %span.by-icon-v02> "
                מועדפים
              %a{:href => ""}
                %span.by-icon-v02> p
                הצגה מחדש של
              %a{:href => ""}
                %span.by-icon-v02> {
                האזור האישי
              %a{:href => ""}
                %span.by-icon-v02> Z
                התנתקות
    -#- if defined?(current_user)
    %button.favorites-btn
      .by-icon-v02 "
      -#%div= t(:x_favorites, x: current_user.favorite_count)
      %div#favorites_count= t(:x_favorites, x: @favorite_items_count || 0)
    = render partial: 'shared/breadcrumbs'
    - unless @header_partial.nil?
      = render partial: @header_partial