config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'

  resource :welcome, only: :index
  get 'welcome/query_by_filter', as: 'query_by_filter'
  get 'welcome/autocomplete_by_filter_tag', as: 'autocomplete_by_filter_tag'
  match 'welcome/search', as: 'search', via: [:get, :post]
  match 'welcome/suggest', as: 'suggest', via: [:get, :post]
  match 'welcome/search_disambig', as: 'search_disambig', via: [:get, :post]
  match 'outline/:id' => 'projects#outline', as: 'outline', via: [:get, :post]
  match 'outline_download/:id' => 'projects#outline_download', as: 'outline_download', via: [:get]

  resources :queries, only: [:show, :destroy] do
    member do
      get 'show'
      post 'show'
    end
  end

  resources :projects, except: [:new] do
    resources :queries, only: [:create]
    resources :ignored_items, only: [:create]
  end

  resources :ignored_items, only: [:destroy]

  resources :response_items, only: [] do
    member do
      post :toggle_favorite
    end
  end

  resources :timelines, only: :index do
    collection do
      get :data
    end
  end
end

app/controllers/welcome_controller.rb
require 'rest-client'

MAX_WIKIDATA_RESULTS = 400

PROP_COORDINATES = 'P625'
PROP_INSTANCE_OF = 'P31'

class WelcomeController < ApplicationController
  before_action :force_json, only: [:autocomplete_by_filter_tag, :query_by_filter]

  def index

  end
  def autocomplete_by_filter_tag
    tag = params[:tag]
    phrase = params[:phrase]
    query = browsing_tree['filters']['wikidata'].find{|f| f['tag'] == tag}['lookup_query']
    if query.present?
      @sparql_results = wikidata_query_as_hash(query)
      #debugger
    else
      head 404
    end
  end
  def query_by_filter
    filter = params[:filter]
    base_query = params[:base_query]
    q = params[:q]
    query = browsing_tree['base_queries']['wikidata'].find{|f| f['tag'] == base_query}['sparql']
    if query.present?
      query = append_where_clause(query, browsing_tree['filters']['wikidata'].find{|f| f['tag'] == filter}['sparql'], [q])
      @sparql_results = wikidata_query_as_hash(query)
    else
      head 404
    end
  end
  def search
    @sara_mode = :search
  end
  def search_disambig
    @filters = {}
    unless params[:base_query].present?
      @sara_mode = :search
      @q = params[:q]
      if @q.present?
        # search Wikidata using the search action of the standard API
        RestClient.get 'https://www.wikidata.org/w/api.php', {params: {action: 'wbsearchentities', search: @q, language: 'he', uselang: 'he', type: 'item', limit: '50', format: 'json'}} do |response, request, result, &block|
          if result.class == Net::HTTPOK
            json = JSON.parse(response.body)
            search_results = json['search']
            # enrich results with images and intro paragraphs
            @results = {}
            ids = []
            search_results.each do |result|
              @results[result['id']] = {label: result.dig('display', 'label', 'value') || '', description: result.dig('display', 'description', 'value') || ''}
              ids << result['id']
            end
            prep_items(ids)
          end
        end
        @sorted_keys = @results.sort_by{|item| item[1][:label]}.map{|arr| arr[0]}
      else
        flash[:error] = 'לא הוזנו די פרטים'
        redirect_to root_path
      end
    else
      @sara_mode = :suggest
      @base_query = browsing_tree['base_queries']['wikidata'].find{|f| f['tag'] == params[:base_query]}
      @query = compose_query(@base_query['sparql'])
      unless @query.nil?
        count = wikidata_count(@base_query['sparql'])
        if count > 0 && count < MAX_WIKIDATA_RESULTS
          @results = wikidata_query_as_qid_hash(@base_query['sparql'],params)
          prep_items(@results.keys)
        end
      end
      unless @results.present?
        @results = []
        @topic_count = count
        flash[:error] = "לא ניתן להציג תוצאות כי יש #{count} תוצאות. יש להוסיף מסננים עד שיהיו פחות מ־#{MAX_WIKIDATA_RESULTS} תוצאות"
      else
        @sorted_keys = @results.sort_by{|item| item[1][:label]}.map{|arr| arr[0]}
      end
    end
  end
  def suggest
    @sara_mode = :suggest
    # prototyping of browsing tree
    @menu = browsing_tree['nodes']
    @base_queries = browsing_tree['base_queries']
    @filters = browsing_tree['filters']
  end
  private
  def browsing_tree
    @browsing_tree || load_browsing_tree
  end
  def force_json
    request.format = :json
  end
  def prep_items(ids)
    # get images, occupations, and life years
    @topic_count = @results.keys.count
    qids = []
    print "DBG: prepping #{ids.count} Wikidata items..."
    ids.each_slice(50) do |id_slice|
      images = {}
      print "."
      slice_ids = id_slice.join('|')
      slice_items = Rails.cache.fetch("entities_#{Digest::SHA256.hexdigest(slice_ids)}", expires_in: 12.hours) do
        Rails.logger.debug "cache miss for entities for #{slice_ids}"
        RestClient.get 'https://www.wikidata.org/w/api.php', {params: {action: 'wbgetentities', ids: slice_ids, language: 'he', uselang: 'he', props: 'sitelinks|claims', format: 'json'}} do |resp, req, res, &block|
          if res.class == Net::HTTPOK
            JSON.parse(resp.body)
          end
        end
      end
      slice_items['entities'].keys.each do |qid|
        item = slice_items['entities'][qid]
        claims = item['claims']

        @results[qid]['instance-of'] = wikimedia_prop_values(claims, PROP_INSTANCE_OF)&.map{|c| c['id']}
        @results[qid]['coordinates'] = first_prop_value(claims, PROP_COORDINATES, nil)

        @results[qid]['wikipedia_url'] = item['sitelinks']['hewiki'] ? 'https://he.wikipedia.org/wiki/'+item['sitelinks']['hewiki']['title'] : ''
        imagename = item['claims']['P18'] ? item['claims']['P18'][0]['mainsnak']['datavalue']['value'] : ''
        images['File:'+imagename] = qid unless imagename.empty?
        unless @results[qid]['instance-of'].nil?
          case
          when @results[qid]['instance-of'].include?('Q5') # human
            @results[qid]['birthyear'] = item['claims']['P569'] ? item['claims']['P569'][0]['mainsnak']['datavalue']['value']['time'][1..4] : ''
            @results[qid]['deathyear'] = item['claims']['P570'] ? item['claims']['P570'][0]['mainsnak']['datavalue']['value']['time'][1..4] : ''
            @results[qid]['occupations'] = item['claims']['P106'].map{|c| c['mainsnak']['datavalue']['value']['id']} if item['claims']['P106']
            @results[qid]['nationality'] = item['claims']['P27'] ? item['claims']['P27'][0]['mainsnak']['datavalue']['value']['id'] : ''
            @results[qid]['benyehuda_url'] = 'https://benyehuda.org/author/'+item['claims']['P7507'][0]['mainsnak']['datavalue']['value'] if item['claims']['P7507']
            @results[qid]['nli_id'] = item['claims']['P8189'][0]['mainsnak']['datavalue']['value'] if item['claims']['P8189']
          when @results[qid]['instance-of'].include?('Q16521'), @results[qid]['instance-of'].include?('Q7075') # organization, library
            @results[qid]['inception'] = item['claims']['P571'] ? item['claims']['P571'][0]['mainsnak']['datavalue']['value']['time'][1..4] : ''
            @results[qid]['country'] = item['claims']['P17'] ? item['claims']['P17'][0]['mainsnak']['datavalue']['value']['id'] : ''
          when @results[qid]['instance-of'].include?('Q486972') # human settlement
            @results[qid]['population'] = item['claims']['P1082'] ? item['claims']['P1082'][0]['mainsnak']['datavalue']['value']['amount'] : ''
            @results[qid]['coordinates'] = item['claims']['P625'] ? item['claims']['P625'][0]['mainsnak']['datavalue']['value'] : ''
            @results[qid]['inception'] = item['claims']['P571'] ? item['claims']['P571'][0]['mainsnak']['datavalue']['value']['time'][1..4] : ''
            @results[qid]['country'] = item['claims']['P17'] ? item['claims']['P17'][0]['mainsnak']['datavalue']['value']['id'] : ''
          end
        end
      end
      # get image thumbnail URLs
      unless images.empty?
        image_titles = images.keys.join('|')
        json3 = Rails.cache.fetch("thumbnails_#{Digest::SHA256.hexdigest(image_titles)}", expires_in: 12.hours) do
          Rails.logger.debug "cache miss for thumbnails for #{image_titles}"
          RestClient.get 'https://commons.wikimedia.org/w/api.php', {params: {action: 'query', prop: 'imageinfo', iiprop: 'url', iiurlwidth: 80, titles: image_titles, format: 'json'}} do |resp3, req3, res3, &block|
            if res3.class == Net::HTTPOK
              JSON.parse(resp3.body)['query']['pages']
            end
          end
        end
        json3.each do |page, data|
          @results[images[data['title']]]['thumbnail'] = data['imageinfo'][0]['thumburl']
        end
      end

      # get the labels for the QID values we collected
      @results.each do |qid, data|
        data.keys.each do |key|
          qids << data[key] if data[key].is_a?(String) && data[key].start_with?('Q')
          if data[key].is_a?(Array)
            data[key].each {|v| qids << v if v.start_with?('Q')}
          end
        end
      end
    end
    @labels = get_labels_for_qids(qids.uniq)
    # TODO: also fetch Wikipedia article intros?
    @timeline_data = prep_timeline_data(@results)

    @map_markers = prep_map_markers(@results)
  end

  def wikimedia_prop_values(claims, prop)
    values = claims[prop]
    return nil if values.nil?
    return claims[prop].map { |item| item['mainsnak']['datavalue']['value']}
  end

  def first_prop_value(claims, prop, default_value = '')
    values = wikimedia_prop_values(claims, prop)
    return values.nil? || values.empty? ? default_value : values[0]
  end

  def prep_timeline_data(results)
    timeline_data = []
    results.each do |qid, data|
      timeline_rec = { 'id' => qid, 'title' => data[:label], 'subtitle' => data[:description]}
      timeline_rec['from'] = {'year' => data['birthyear'].to_i} if data['birthyear'].present? && data['birthyear'].to_i != nil
      timeline_rec['from'] = {'year' => data['inception'].to_i} if data['inception'].present? && data['inception'].to_i != nil # mutually exclusive with birthyear
      timeline_rec['to'] = {'year' => data['deathyear'].to_i} if data['deathyear'].present? && data['deathyear'].to_i != nil
      timeline_rec['imageUrl'] = data['thumbnail'] if data['thumbnail'].present?
      timeline_data << timeline_rec if timeline_rec['to'].present? || timeline_rec['from'].present? # no point in adding records that cannot be displayed on the timeline
    end
    return timeline_data
  end

  def prep_map_markers(items)
    result = []
    items.each do |qid, data|
      coordinates = data['coordinates']
      next if coordinates.blank?
      result << coordinates.slice('latitude', 'longitude').merge(title: data[:label], icon: data['thumbnail'], qid: qid)
    end

    return result
  end

  def compose_query(base_query)
    ret = base_query
    if params[:fromdate].present? || params[:todate].present?
      @filters['date_filter'] = params[:date_filter]
      @filters['fromdate'] = params[:fromdate] if params[:fromdate].present?

app/views/welcome/index.html.haml
#home-initial.top-element
  .full-screen-search-area
    .bubble-with-top
      .bubble-top
      .bubble
        .flex-headline-space-between
          %div
            %p= t('.intro_html')
          %a.by-icon-v02{:href => "#"} -
    .home-switch
      .home-switch-option.focus-search-option
        = form_tag search_disambig_path, method: :get, id: 'search-form' do
          %p{style:'margin-top:50px'}= t('nav.focused_search')
          .focus-search-bar
            %input{ name: 'q', placeholder: t(:what_would_you_like_me_to_research_for_you)}/
            %button.sara-button.button-primary{:style => "display: flex"}
              = t(:search)
      .home-switch-option.suggestions-search-option{style: 'cursor: pointer;'}
        %p{style:'margin-top:50px'}= t('nav.suggest_topics')
        %div{:style => "margin-right:36px; margin-top: 48px"}
          %a.white{:href => ""} היום בהיסטוריה
        %div{:style => "margin-right:240px; margin-top: 0px"}
          %a.white{:href => ""} יהדות
        %div{:style => "margin-right:90px; margin-top: 12px"}
          %a.white{:href => ""} תולדות העם היהודי
        %div{:style => "margin-right:300px; margin-top: 12px"}
          %a.white{:href => ""} אימפריות
        %div{:style => "margin-right:120px; margin-top: 8px"}
          %a.white{:href => ""} קונפליקטים ומלחמות
        %div{:style => "margin-right:76px; margin-top: 18px"}
          %a.white{:href => ""} ארץ ישראל
        %div{:style => "margin-right:270px; margin-top: 12px"}
          %a.white{:href => ""} מקומות
        %div{:style => "margin-right:136px; margin-top: 8px"}
          %a.white{:href => ""} אישים ומנהיגים

:javascript
  $(document).ready(function() {
    $('.suggestions-search-option').click(function() {
      window.location.href = '#{suggest_path}';
    });
  });

app/views/welcome/search.html.haml
.full-screen-search-area.focus-search.vcenter
  = form_tag search_disambig_path, method: :get, id: 'search-form' do
    .focus-search-bar
      %input#q{name: 'q', placeholder: t(:what_would_you_like_me_to_research_for_you)}
      %button.sara-button.button-primary{:style => "display: flex"}
        = t(:search)
        .by-icon-v02 1

app/views/welcome/search_disambig.html.haml
= content_for :head do
  %script{ src: "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_JS_API_KEY']}" }
  %script{ src: "https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js" }

%script{ type: 'text/javascript', charset:'utf-8', src: asset_url('histropedia-1.2.0.js')}
%div#spinnerdiv{style: 'display: none; top: 50%; left: 50%;'}
  #floatingCirclesG
    #frotateG_01.f_circleG
    #frotateG_02.f_circleG
    #frotateG_03.f_circleG
    #frotateG_04.f_circleG
    #frotateG_05.f_circleG
    #frotateG_06.f_circleG
    #frotateG_07.f_circleG
    #frotateG_08.f_circleG
.full-screen-area
  .search-content
    .subjects-fixed-top-elements
      %div{:style => "margin-right: 220px"}
        .filter-tags-area
          .tags-right
            %p
              %strong= t(:x_topics_found, x: @topic_count)
            .tag-line
              - if @q.present?
                .tag
                  = t(:search_string, q: @q)
                  %a.by-icon-v02{:href => "#"} -
          .left-bottons-area
            %button#search-subject-results-button.sara-button.button-primary.disabled
              = t(:search_this_topic)
              .by-icon-v02 1
        .view-switch-line
          = t(:display_colon)
          .small-switch
            %button#list.small-switch-option.sort-by.active= t(:display_list)
            %button#timeline.small-switch-option.sort-by= t(:display_timeline)
            %button#map.small-switch-option.sort-by= t(:display_map)
    = form_tag(search_disambig_path, method: :post, id: 'filters_form') do
      = hidden_field_tag :base_query, params['base_query']
      = hidden_field_tag :qid, params['qid']
      = hidden_field_tag :q, params['q']
      .filters#filters
        .subjects-filter
          .flex-headline-space-between.vertical-expand{"data-bs-target" => "#time_filter", "data-bs-toggle" => "collapse"}
            %p.headline-3= t('filters.by_year')
            .sara-icon c
          #time_filter{"data-bs-parent" => "#filters", class: "collapse #{(@filters['fromdate'].present? || @filters['todate'].present?) ? 'show' : ''}"}
            %div{style: "display: flex; flex-direction: column; gap: 12px;"}
              %select#filter_by_time{:name => "date_filter"}
                %option{:value => "birth_date", selected: @filters['date_filter'] == 'birth_date' ? true : false}= t('filters.birth_date')
                %option{:value => "death_date", selected: @filters['date_filter'] == 'death_date' ? true : false}= t('filters.death_date')
                %option{:value => "inception_date", selected: @filters['date_filter'] == 'inception_date' ? true : false}= t('filters.inception_date')
              .dates-range
                %input#fromdate{"data-target" => "#fromdate", "data-toggle" => "datetimepicker", :name => "fromdate", :placeholder => t(:year), value: @filters['fromdate']}/
                %div= t(:to)
                %input#todate{"data-target" => "#todate", "data-toggle" => "datetimepicker", :name => "todate", :placeholder => t(:year), value: @filters['todate']}/
              - if @filters['fromdate'].present? || @filters['todate'].present?
                .bottom-buttons-line
                  %a#clear_dates{:href => ""}= t('filters.cancel')
              - else
                .bottom-buttons-line
                  = submit_tag t('filters.add'), class: 'sara-button button-primary filters-submit'
      
        .subjects-filter
          .flex-headline-space-between
            %p.headline-3 סינון לפי מיקום
            .sara-icon m
          .bottom-buttons-line
            %a{:href => ""} הוספת מסנן
        .subjects-filter
          .flex-headline-space-between.vertical-expand{"data-bs-target" => "#gender_f", "data-bs-toggle" => "collapse"}
            %p.headline-3= t('filters.by_gender')
            .sara-icon g
          #gender_f{"data-bs-parent" => "#filters", class: "collapse #{@filters['gender'].present? ? 'show' : ''}"}
            %div{style: "display: flex; flex-direction: column; gap: 12px;"}
              %select#filter_by_gender{:name => "gender"}
                %option{:value => '', selected: true}= ''
                %option{:value => "Q6581097", selected: @filters['gender'] == 'Q6581097' ? true : false}= t('filters.male')
                %option{:value => "Q6581072", selected: @filters['gender'] == 'Q6581072' ? true : false}= t('filters.female')
                %option{:value => "other", selected: @filters['gender'] == 'other' ? true : false}= t('filters.other')
              - if @filters['gender'].present?
                .bottom-buttons-line
                  %a#clear_gender{:href => ""}= t('filters.cancel')
              - else
                .bottom-buttons-line
                  = submit_tag t('filters.add'), class: 'sara-button button-primary filters-submit'

    .subjects
      .results-area
        .results-list{style: 'margin-top: 121px;'}
          - if @results.present?
            - @sorted_keys.each do |qid|
              .result-item
                - if @results[qid]['thumbnail'].present? # if result has a picture
                  .subject-picture
                    %img{alt: @results[qid][:label], src: @results[qid]['thumbnail']}
                .result-texts
                  .flex-headline-space-between
                    - if @results[qid]['instance-of'].present? && @results[qid]['instance-of'].include?('Q5') # human
                      - birth = @results[qid]['birthyear'].present? ? @results[qid]['birthyear'] : '?'
                      - death = @results[qid]['deathyear'].present? ? @results[qid]['deathyear'] : ''
                      %p.headline-3= @results[qid][:label]+ " (#{birth}–#{death})"
                      = @results[qid][:description]
                    - else
                      %p.headline-3= @results[qid][:label]
                      = @results[qid][:description]
                    .result-sources-icons
                      - if @results[qid]['wikipedia_url'].present?
                        = image_tag 'Wikipedia_logo_24.png', {alt: t(:wikipedia), title: t(:wikipedia)} 
                      - if @results[qid]['nli_id'].present?
                        = image_tag 'nli_logo_24.png', {alt: t(:nli), title: t(:nli)}
                      - if @results[qid]['benyehuda_url'].present?
                        = image_tag 'pby_logo_24.png', {alt: t(:pby), title: t(:pby)}
                  .results-limited-text
                    - if @results[qid]['occupations'].present?
                      %p
                        = t(:occupations)+': '
                        = @results[qid]['occupations'].map{|occ| @labels[occ] || '...'}.join('; ')
                      %p
                        = t(:nationality)+': '
                        = @labels[@results[qid]['nationality']]
                    - if @results[qid]['wikipedia_url'].present?
                      %a{href: @results[qid]['wikipedia_url']}= t(:to_wikipedia)
          - else
            %h3= t('filters.too_many_results', count: @topic_count)
        .timeline{style:'margin-top:121px;display:none;'}
          #histropedia-timeline
        .map{style:'margin-top:121px;display:none;'}
          #map_container{ style: "height: 600px; width: 1024px;" }
= form_for([Project.last, Query.new]) do |f|
  = f.hidden_field :text, class: 'form-control', id: 'search_q'
  = f.submit t('projects.show.run'), style: 'display:none'

:javascript
  function startModal(id) {
    $("body").prepend("<div id='PopupMask' style='position:fixed;width:100%;height:100%;z-index:10;background-color:gray;'></div>");
    $("#PopupMask").css('opacity', 0.5);
    $("#"+id).css( "z-index" , 11 );
    $("#"+id).css( "position" , "fixed" );
    $("#"+id).css( "display" , "block" );
  }

  function selectItem(qid, search_q) {
    $('#qid').val(qid);
    $('#search_q').val(search_q);
    $('#search-subject-results-button').removeClass('disabled');
  };


  $(document).ready(function() {
    $('.result-item').click(function(e) {
      e.stopPropagation();
      $('.result-item').removeClass('active');
      $(this).addClass('active');
      $('#search-subject-results-button').removeClass('disabled');
    });
    $('#search-subject-results-button').click(function(e) {
      if(!$(this).hasClass('disabled')) {
        if($('.results-list').css('display') != 'none') {
          $('#search_q').val($('div.result-item.active > div.result-texts > div.flex-headline-space-between > p').text());
        }
        startModal('spinnerdiv');
        $('form').submit();
      } else alert('#{ t(:please_select_topic) }');
    });
    $('#clear_dates').click(function(e) {
      e.preventDefault();
      $('#fromdate').val('');
      $('#todate').val('');
      startModal('spinnerdiv');
      $('#filters_form').submit();
    });
    $('#clear_gender').click(function(e) {
      e.preventDefault();
      $('#filter_by_gender').val('');
      startModal('spinnerdiv');
      $('#filters_form').submit();
    });
    $('.filters-submit').click(function(e) {
      startModal('spinnerdiv');
    });
    $('#timeline').click(function(e) {
      e.preventDefault();
      $('.results-list').hide();
      $('.timeline').show();
      $('#timeline').addClass('active');
      $('#list').removeClass('active');
      $('#map').removeClass('active');
      $('.map').hide();
    });
    $('#map').click(function(e) {
      e.preventDefault();
      $('.results-list').hide();
      $('#list').removeClass('active');
      $('.timeline').hide();
      $('#timeline').removeClass('active');
      $('.map').show();
      $('#map').addClass('active');
    });
    $('#list').click(function(e) {
      e.preventDefault();
      $('.results-list').show();
      $('#list').addClass('active');
      $('.timeline').hide();
      $('#timeline').removeClass('active');
      $('#map').removeClass('active');
      $('.map').hide();
    });

    try {
      // prep timeline
      const container = document.getElementById('histropedia-timeline');
      if (container != null) {
        const data = #{raw @timeline_data.to_json} || [];
        let min = null;
        let minVal = Infinity;
        let max = null;
        let maxVal = 0;
        data.forEach((item) => {
          if(item.from != null) {
            const val = item.from.year * 10000; // + item.from.month * 100 + item.from.day;
            if (val < minVal) {
              minVal = val;
              min = item;
            }
            if (val > maxVal) {
              maxVal = val;
              max = item;
            }
          }
        });
        const timeline = new Histropedia.Timeline(
          container,
          {
            height: 700,
            article: {distanceToMainLine: 100},
            initialDate: ((max && min) ? (min.from.year + (max.from.year - min.from.year) / 2) : (min ? min.from : 19800000)),
            zoom: {
              initial: 30,
              minimum: 24,
              maximum: 40,
              wheelStep: 1
            },
            article: { autoStacking: {topGap: 0, fitToHeight: false } },
            onArticleClick: function(article) { selectItem(article.id, article.title); },
            onArticleDoubleClick: function(article) { }
          }
        );
        timeline.load(data);
      }
    } catch (e) {
      console.error(e);
    }

    const map = new google.maps.Map(
        document.getElementById('map_container'),
        {
          center: { lat: 31.771959, lng: 35.217018 }, /* coordinates of Jerusalem */
          zoom: 2
        }
    );

    const markers = [];

    const data = #{raw @map_markers.to_json} || [];
    data.forEach(item => {
      const marker = new google.maps.Marker({
        position: { lat: item['latitude'], lng: item['longitude'] },
        map,
        title: item['title'],
        icon: item['icon']
      });
      marker.addListener("click", () => { selectItem(item['qid'], item['title']); });
      markers.push(marker);
    });

    new markerClusterer.MarkerClusterer({ markers, map });
  });

app/views/welcome/suggest.html.haml
.full-screen-area
  .search-content.browsing-route
    %form.works_filters{"accept-charset" => "UTF-8", :action => "", "data-remote" => "true", :method => "post"}
      %input{:name => "utf8", :type => "hidden", :value => "✓"}/
      %input#sort_by{:name => "sort_by", :type => "hidden", :value => "alphabetical_asc"}/
      .filters-panel.categories
        .sort-type
          - ordinal = 0
          - @menu.each do |node|
            - ordinal += 1
            = render partial: 'shared/menu_item', locals: { node: node, level: 1, ordinal: ordinal, parent: '.categories' }

:javascript
  $(document).ready(function() {
    $('.collapse').collapse('hide');

    $('*[data-behavior=autocomplete]').each(function() {
      var iid = $(this).attr('id');
      var tag = $(this).data('tag');
      options = { 
        url: function(phrase) { return "#{autocomplete_by_filter_tag_path}?phrase=" + phrase + "&tag=" + tag + "&format=json";}, 
        getValue: "name",
        list: { 
      		match: { enabled: true },
          onChooseEvent: function() {
            var value = $('#'+iid).getSelectedItemData().qid;
            $('#'+iid+'_value').val(value);
          }
        }
      };
      $(this).easyAutocomplete(options);
    });
    $('.run_query').click(function() {
      $(this).text('querying...');
      $(this).prop('disabled', true);
      var base_query = $(this).data('base-query');
      var tag = $(this).data('tag');
      var params = [];

      $.post("#{query_by_filter_path}",
          { base_query: base_query, format: 'json', filter: tag, params: params },
      ).done(function(data) {
        data.forEach(function(item) {
          $('#result_list').append('<li>'+item.name+' ('+item.qid.replace('wd:','')+')</li>');
        });
      });

      url = "#{query_by_filter_path}?base_query=" + base_query + "&filter=" + tag + "&q=" + $('#param_'+tag+'_0_value').val() + "&format=json";
      $.ajax({type: 'post', url: url, context: this, success: function(response, status){
        response.forEach(function(item) {
          $('#result_list').append('<li>'+item.name+' ('+item.qid.replace('wd:','')+')</li>');
        });
        $(this).text('run query!');
        $(this).prop('disabled', false);
        console.log(response);
      }});

    }); 
  });