config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'

  resource :welcome, only: :index
  get 'welcome/query_by_filter', as: 'query_by_filter'
  get 'welcome/autocomplete_by_filter_tag', as: 'autocomplete_by_filter_tag'
  match 'welcome/search', as: 'search', via: [:get, :post]
  match 'welcome/suggest', as: 'suggest', via: [:get, :post]
  match 'welcome/search_disambig', as: 'search_disambig', via: [:get, :post]
  match 'outline/:id' => 'projects#outline', as: 'outline', via: [:get, :post]
  match 'outline_download/:id' => 'projects#outline_download', as: 'outline_download', via: [:get]

  resources :queries, only: [:show, :destroy] do
    member do
      get 'show'
      post 'show'
    end
  end

  resources :projects, except: [:new] do
    resources :queries, only: [:create]
    resources :ignored_items, only: [:create]
  end

  resources :ignored_items, only: [:destroy]

  resources :response_items, only: [] do
    member do
      post :toggle_favorite
    end
  end

  resources :timelines, only: :index do
    collection do
      get :data
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :response_items, inverse_of: :project, dependent: :destroy
  has_many :queries, inverse_of: :project, dependent: :destroy
  has_many :ignored_items, inverse_of: :project, dependent: :destroy
  validates :title, presence: true

  def favorite_items
    # We can have duplicates of favorite items in db (if same item was returned by different queries of same project)
    # That's why  we need an additional filter to hide duplicates (we will return only latest item from all items with
    # same external_id/source)
    # TODO: create a better solution for duplicate item, after POC is presented
    #   see https://github.com/projectbenyehuda/sara/issues/13#issuecomment-1310482546
    ResponseItem.
      where(project_id: self.id).
      where(favorite: true).
      where(
        <<~sql
          not exists (
            select 1 from
              response_items ri
            where
              ri.source = response_items.source
              and ri.external_id = response_items.external_id
              and ri.project_id = response_items.project_id
              and ri.id > response_items.id
          )
        sql
      )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_model, except: [:index, :create]

  def index
    @projects = Project.order(created_at: :desc)
  end

  def create
    p = Project.new(params.require(:project).permit(:title))
    if p.save
      flash.notice = t('.success')
      redirect_to p
    else
      flash.alert = t('.failed', errors: p.errors.full_messages.join(', '))
      redirect_to action: :index
    end
  end

  def edit

  end

  def update
    attrs = params.require(:project).permit(:title)
    @project.attributes = attrs
    if @project.save
      redirect_to @project, notice: t('.success')
    else
      flash.now.alert = t('.failed', errors: @project.errors.full_messages.join(', '))
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @queries = @project.queries.select(:id, :created_at, :text)
                       .select('count(*) as responses_quantity')
                       .left_joins(:response_items)
                       .group(Arel.sql('queries.id'))
                       .order(:created_at)
  end

  def destroy
    @project.destroy!
    redirect_to action: :index
  end

  def outline
    @sara_mode = :outline
    @favorite_items = @project.favorite_items
    @wikipedia_url = ''
    @wikipedia_snippet = ''
    @outline = prep_outline
  end

  def outline_download
    @favorite_items = @project.favorite_items
    @outline = prep_outline
    send_data "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"he\" lang=\"he\" dir=\"rtl\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /></head><body dir='rtl' align='right'><div dir=\"rtl\" align=\"right\">#{@outline}</div></body></html>", filename: t('.filename', title: @project.title)
  end
  private

  def set_model
    id = params[:id]
    @project = Project.find(id)
  end

  def prep_outline_item(item)
    ret = "<p class=\"headline-4\"><a href=\"#{item.url}\">#{item.title}</a> (#{textify_media_type(item.media_type)})</p>"
    ret += "<div class='subject-picture'><a href=\"#{item.media_url}\"><img src=\"#{item.thumbnail_url}\" /></a></div>" if item.thumbnail_url.present?
    ret += "<div class='outline-content-texts'>#{item.text}<p /><p><strong>#{t(:source)}</strong>:#{textify_citation(item)}</p></div>"
    return ret
  end
  def prep_outline
    ret = "<h2>#{@project.title} – #{t('.sources')}</h2>"
    # ret += "<p><img src=\"#{item.image_url}\" /></p>"
    # ret += "<p>#{item.description}</p>"
    # if item.wikipedia_url.present? && item.wikipedia_snippet.present?
      # ret += "<h3><a href=\"#{item.wikipedia_url}\">#{t(:wikipedia)}</a></h3>"
      # ret += "<p>#{item.wikipedia_snippet}</p>"
    # end
    @project.favorite_items.each do |item|
      ret += prep_outline_item(item)
    end
    ret
=begin             .outline-content-item
          .outline-content-texts
            %a{:href => ""} מתוך ויקיפדיה העברית
            %p הטקסט מוגש בכפוף לרשיון
            %p ייחוס-שיתוף זהה Creative commons 3.0
        .outline-content-item
          .outline-content-texts
            %p.headline-4 יעקב פיכמן: מבחר מאמרי ביקורת על יצירתו - מבוא וביבליוגרפיה. נורית גוברין
            %p תל אביב: עם עובד: 1971
            %p גוברין, נ׳. (1971). יעקב פיכמן: מבחר מאמרי ביקורת על יצירתו [מבוא וביבליוגרפיה]. [גרסה אלקטרונית]. https://benyehuda.org/read/19154. פרויקט בן־יהודה.
        .outline-content-item
          .outline-content-texts
            %p.headline-4 הסיפור ״מצולה״ ומקורותיו
            %p בתוך: ״מעגלים״
            %p רמת-גן: אגודת הסופרים העברים בישראל ליד הוצאת מסדה, 1975
            %p גוברין, נ׳. (1975). הסיפור ״מצולה״ ומקורותיו [גרסה אלקטרונית]. https://benyehuda.org/read/25308. פרויקט בן־יהודה. 10-01
=end
  end
end

app/views/projects/edit.html.haml
%h1= t('.header')
= form_for @project do |f|
  .row
    .col-sm-2
      = label_tag :title, nil, class: 'control-label'
    .col-sm-6
      = f.text_field :title, class: 'form-control'

    .col-sm-2
      .btn-group
        = f.submit nil, class: 'btn btn-primary'
        = link_to t(:cancel), @project, class: 'btn btn-light'

app/views/projects/index.html.haml
= form_for(Project.new) do |f|
  .row
    .col-sm-3
    .col-sm-1
      = f.label t('.create_new'), class: 'form-label'
    .col-sm-4
      = f.text_field :title, placeholder: true, class: 'form-control'
    .col-sm-2
      = f.submit t('.create'), class: 'btn btn-primary'

%table.table
  %thead
    %th= t('activerecord.attributes.query.title')
    %th= t('activerecord.attributes.default.created_at')
    %th= t('activerecord.attributes.default.updated_at')
  %tbody
    - @projects.each do |p|
      %tr
        %td= link_to p.title, p
        %td= p.created_at
        %td= p.updated_at

app/views/projects/outline.html.haml
.full-screen-area
  .search-content
    .outline-sources-panel
      .outline-sources
        .source-type-line
          %a.headline-4{:href => ""} על אודות היוצר/ת
    .outline-fixed-top-elements
      .outline-top-area.outline-top-right
        .outline-right
          %span.by-icon-v02 p
          %p.headline-3= t(:sources)
      .outline-top-area.outline-top-left
        .outline-right
          %span.by-icon-v02 H
          %p.headline-3= t('projects.outline.outline')
        .left-bottons-area
          %a{href: outline_download_path(id: @project.id), target: '_blank'}
            %button#download.sara-button.button-primary
              .by-icon-v02.larger-icon> J
              = t(:download_as_file)
          %button#close.sara-button.button-primary
            .by-icon-v02> -
            יציאה
    .outline-page-container{style: 'margin-top: 56px;'}
      .outline-page
        != @outline

app/views/projects/show.html.haml
%h1= t('.header', title: @project.title)
= link_to t(:edit), edit_project_path(@project)

= form_for([@project, Query.new]) do |f|
  .row
    .col-sm-3
    .col-sm-1
      = f.label t('.create_new'), class: 'form-label'
    .col-sm-4
      = f.text_field :text, placeholder: true, class: 'form-control'
    .col-sm-2
      = f.submit t('.run'), class: 'btn btn-primary'

%h2= t('.stored_queries')

%table.table
  %thead
    %th= t('activerecord.attributes.default.created_at')
    %th= t('activerecord.attributes.query.text')
    %th= t('.responses_quantity')
    %th
  %tbody
    - @queries.each do |q|
      %tr
        %td= q.created_at
        %td= link_to q.text, q
        %td= q.responses_quantity
        %td
          = button_to t('.destroy_query'), "/queries/#{q.id}", method: :delete, class: 'btn btn-danger'